version: '2'
services:
  php:
    build: ./docker/php
    ports:
     - "81:80"
     - "443:443"
    volumes:
     - .:/var/www/html
     - ./docker/apache:/etc/apache2/sites-enabled:ro
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
